# Generated by Django 4.0 on 2021-12-18 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_location_alter_profile_profile_image_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
