# Generated by Django 4.0 on 2021-12-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='This is the space for "Location"', max_length=200, null=True),
        ),
    ]
