# Generated by Django 4.0 on 2021-12-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0002_tag_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='project',
            new_name='projectf',
        ),
    ]
