# Generated by Django 4.0 on 2021-12-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0004_rename_projectf_reviews_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple',
            name='tag',
            field=models.ManyToManyField(blank=True, to='simple.Tag'),
        ),
        migrations.AlterField(
            model_name='simple',
            name='demo_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
