# Generated by Django 4.0 on 2021-12-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0006_rename_simple_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
