# Generated by Django 4.0 on 2021-12-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple', '0009_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='codesniper.png', null=True, upload_to=''),
        ),
    ]
